apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    #PLACEHOLDER: Add label here
    release: prometheus
  name: api-rules
spec:
  groups:
    - name: api
      rules:
        - alert: down
          expr: up==0
          for: 0m
          labels:
            serverity: critical
          annotations:
            summary: Prometheus target missing {{$labels.instance}}	
