# user test can get and list secret in name space Europe
# For Testing ==>  k -n europe auth can-i get secrets --as=test
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: roletwo
  namespace: europe
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rolebindingtwo
  namespace: europe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: roletwo
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: test
